### ISSUE TITLE
Add a Requirements.txt rather than use conda config/channels

### ISSUE THREAD

**Issue by taddyb** [mhpi/generic_deltamodel#39]
### Summary

- Given PyTorch no longer has binaries on CONDA forge, it may be wise to use requirements.txt rather than an env file
- This is more _generic_ and can still support CONDA

### Actions

- change .yaml config to a requirements.txt, or have the dependencies specified in the `pyproject.toml`

### Considerations

Proof there is no support for CONDA

<img width="886" alt="Image" src="https://github.com/user-attachments/assets/bf53d58d-9c2b-46a2-b073-7766f115c01f" />

The current env yaml
```yaml
name: deltamodel
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-mutex=1.0
  - pytorch::torchaudio=2.5.1
  - pytorch::torchvision=0.20.1
.
.
.
```
